
RETURNCODES = 
	BAD_REQUEST: 400
	INTERNAL_ERROR: 500
	UNAUTHORIZED: 401
	OK: 200
	CREATED: 201
	FORBIDDEN: 403
	NOT_FOUND: 404

RETURNSTRINGS = 
  RETURNCODES.BAD_REQUEST: "Bad Request"
  RETURNCODES.INTERNAL_ERROR: "Internal Server Error"
  RETURNCODES.UNAUTHORIZED: "Unauthorized"
  RETURNCODES.FORBIDDEN: "Forbidden"
  RETURNCODES.NOT_FOUND: "Not Found"
	RETURNCODES.OK: 'OK'
	RETURNCODES.CREATED: 'Created'


exports.RETURNCODES = RETURNCODES
exports.RETURNSTRINGS = RETURNSTRINGS