
RETURNCODES = 
	BAD_REQUEST: 400
	INTERNAL_ERROR: 500
	UNAUTHORIZED: 401
	OK: 200
	CREATED: 201
	FORBIDDEN: 403
	NOT_FOUND: 404

#console.log RETURNCODES

RETURNSTRINGS = {}
RETURNSTRINGS[RETURNCODES.BAD_REQUEST] = "Bad Request"
RETURNSTRINGS[RETURNCODES.INTERNAL_ERROR] = "Internal Server Error"
RETURNSTRINGS[RETURNCODES.UNAUTHORIZED] = "Unauthorized"
RETURNSTRINGS[RETURNCODES.FORBIDDEN] = "Forbidden"
RETURNSTRINGS[RETURNCODES.NOT_FOUND] ="Not Found"
RETURNSTRINGS[RETURNCODES.OK] = 'OK'
RETURNSTRINGS[RETURNCODES.CREATED] = 'Created'

exports.RETURNCODES = RETURNCODES
exports.RETURNSTRINGS = RETURNSTRINGS